menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10  # 메뉴에서의 순서를 조정할 수 있습니다


params:
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  defaultTheme: auto
  ShowBreadCrumbs: true
  cover:
    linkFullImages: false
    hiddenInList: true